version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - /home/taoqf/work/data/postgre:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: dfactory
      POSTGRES_USER: dfactory
      POSTGRES_PASSWORD: 01factory
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
