version: '3.3'

services:
  01factory:
    stdin_open: true
    tty: true
    working_dir: /01factory
    image: taoqf/node:latest
    volumes:
      - ./data/01factory:/01factory
      - ~/.ssh:/root/.ssh
    ports: 
      - 3000:3000
